version: "3.7"
services:
  web-ci:
    build: .
    ports:
      - "8010:80"
    volumes:
      - ./:/var/www/html
      - ../../Core/:/var/www/core
    extra_hosts:
      - 'host.docker.internal:host-gateway'